BrokerAddress = "127.0.0.1:4222"
CentralNodeName = "central"
ConfigFolder = "./etc"
DefaultMessageRetries = 3
DefaultMessageTimeout = 5
NodeName = "central"
ProfilingPort = ""
PromHostAndPort = ""
PublisherServiceSayhello = 30
StartSayHelloSubscriber = false
SubscribersDataFolder = "./data"

[StartCentralErrorLogger]
  OK = true
  Values = ["*"]
