BrokerAddress = "127.0.0.1:4222"
CentralNodeName = "central"
ConfigFolder = "./etc"
DefaultMessageRetries = 3
DefaultMessageTimeout = 5
NodeName = "central"
ProfilingPort = ""
PromHostAndPort = ":2112"
StartPubSayHello = 0
SubscribersDataFolder = "./data"

[StartSubCLICommand]
  OK = true
  Values = ["*"]

[StartSubCLICommandReply]
  OK = true
  Values = ["*"]

[StartSubCLICommandRequest]
  OK = true
  Values = ["*"]

[StartSubCLICommandRequestNOSEQ]
  OK = true
  Values = ["*"]

[StartSubEchoReply]
  OK = true
  Values = ["*"]

[StartSubEchoRequest]
  OK = true
  Values = ["*"]

[StartSubErrorLog]
  OK = true
  Values = ["*"]

[StartSubOpCommand]
  OK = false
  Values = []

[StartSubSayHello]
  OK = true
  Values = ["*"]

[StartSubTextLogging]
  OK = true
  Values = ["*"]
