BrokerAddress = "0"
CentralNodeName = "central"
ConfigFolder = "./etc"
DefaultMessageRetries = 3
DefaultMessageTimeout = 5
NodeName = "central"
ProfilingPort = "6060"
PromHostAndPort = ":2112"
PublisherServiceSayhello = 0
StartCentralErrorLogger = false
StartSayHelloSubscriber = false
SubscribersDataFolder = "./data"
