BrokerAddress = "127.0.0.1:4222"
CentralNodeName = "central"
ConfigFolder = "./etc"
DefaultMessageRetries = 3
DefaultMessageTimeout = 5
NodeName = "central"
ProfilingPort = ""
PromHostAndPort = ":2112"
StartPubREQHello = 0
SubscribersDataFolder = "./data"

[StartSubErrorLog]
  OK = true
  Values = ["*"]

[StartSubREQCliCommand]
  OK = true
  Values = ["*"]

[StartSubREQHello]
  OK = true
  Values = ["*"]

[StartSubREQPing]
  OK = true
  Values = ["*"]

[StartSubREQPong]
  OK = true
  Values = ["*"]

[StartSubREQTextToConsole]
  OK = true
  Values = ["*"]

[StartSubREQTextToLogFile]
  OK = true
  Values = ["*"]

[StartSubREQnCliCommand]
  OK = true
  Values = ["*"]
