BrokerAddress = "127.0.0.1:4222"
CentralNodeName = "central"
ConfigFolder = "./etc"
DefaultMessageRetries = 3
DefaultMessageTimeout = 5
NodeName = "central"
ProfilingPort = ""
PromHostAndPort = ":2112"
StartPubReqHello = 0
SubscribersDataFolder = "./data"

[StartSubEchoReply]
  OK = true
  Values = ["*"]

[StartSubEchoRequest]
  OK = true
  Values = ["*"]

[StartSubErrorLog]
  OK = true
  Values = ["*"]

[StartSubREQCliCommand]
  OK = true
  Values = ["*"]

[StartSubREQTextToConsole]
  OK = true
  Values = ["*"]

[StartSubREQTextToLogFile]
  OK = true
  Values = ["*"]

[StartSubREQnCliCommand]
  OK = true
  Values = ["*"]

[StartSubReqHello]
  OK = true
  Values = ["*"]
